export const ChristmasGreetings: Record<string, string> = {
  Spanish: "¡Feliz Navidad!",
  English: "Merry Christmas!",
  French: "Joyeux Noël !",
  German: "Frohe Weihnachten!",
  Italian: "Buon Natale!",
  Portuguese: "Feliz Natal!",
  Dutch: "Vrolijk Kerstfeest!",
  Russian: "С Рождеством!",
  Chinese: "圣诞快乐！",
  Japanese: "メリークリスマス！",
  Korean: "메리 크리스마스!",
  Arabic: "عيد ميلاد سعيد!",
  Greek: "Καλά Χριστούγεννα!",
  Hebrew: "חג מולד שמח!",
  Hindi: "शुभ क्रिसमस!",
  Turkish: "Mutlu Noeller!",
  Swedish: "God Jul!",
  Danish: "Glædelig Jul!",
  Finnish: "Hyvää Joulua!",
  Norwegian: "God Jul!",
  Polish: "Wesołych Świąt Bożego Narodzenia!",
  Czech: "Veselé Vánoce!",
  Hungarian: "Boldog Karácsonyt!",
  Romanian: "Crăciun Fericit!",
  Bulgarian: "Весела Коледа!",
  Croatian: "Sretan Božić!",
  Serbian: "Срећан Божић!",
};